package com.netreality.vertie.reveng;

// Generated Sep 7, 2014 6:03:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * Carnivaltermsindextbl generated by hbm2java
 */
public class Carnivaltermsindextbl implements java.io.Serializable {

	private Integer termEntryId;
	private String domainTerm;
	private String termUrl;
	private Double termRank;
	private Integer termLocation;

	public Carnivaltermsindextbl() {
	}

	public Carnivaltermsindextbl(String domainTerm, String termUrl) {
		this.domainTerm = domainTerm;
		this.termUrl = termUrl;
	}

	public Carnivaltermsindextbl(String domainTerm, String termUrl,
			Double termRank, Integer termLocation) {
		this.domainTerm = domainTerm;
		this.termUrl = termUrl;
		this.termRank = termRank;
		this.termLocation = termLocation;
	}

	public Integer getTermEntryId() {
		return this.termEntryId;
	}

	public void setTermEntryId(Integer termEntryId) {
		this.termEntryId = termEntryId;
	}

	public String getDomainTerm() {
		return this.domainTerm;
	}

	public void setDomainTerm(String domainTerm) {
		this.domainTerm = domainTerm;
	}

	public String getTermUrl() {
		return this.termUrl;
	}

	public void setTermUrl(String termUrl) {
		this.termUrl = termUrl;
	}

	public Double getTermRank() {
		return this.termRank;
	}

	public void setTermRank(Double termRank) {
		this.termRank = termRank;
	}

	public Integer getTermLocation() {
		return this.termLocation;
	}

	public void setTermLocation(Integer termLocation) {
		this.termLocation = termLocation;
	}

}
