package com.netreality.vertie.reveng;

// Generated Dec 25, 2014 7:59:32 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Tblrecentsearches generated by hbm2java
 */
public class Tblrecentsearches implements java.io.Serializable {

	private Integer searchId;
	private String searchWords;
	private String siteReferalPage;
	private Date createdDate;
	private String createdBy;
	private String updatedBy;
	private Date updatedDate;
	private String referedIpaddress;

	public Tblrecentsearches() {
	}

	public Tblrecentsearches(String searchWords, Date createdDate) {
		this.searchWords = searchWords;
		this.createdDate = createdDate;
	}

	public Tblrecentsearches(String searchWords, String siteReferalPage,
			Date createdDate, String createdBy, String updatedBy,
			Date updatedDate, String referedIpaddress) {
		this.searchWords = searchWords;
		this.siteReferalPage = siteReferalPage;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.referedIpaddress = referedIpaddress;
	}

	public Integer getSearchId() {
		return this.searchId;
	}

	public void setSearchId(Integer searchId) {
		this.searchId = searchId;
	}

	public String getSearchWords() {
		return this.searchWords;
	}

	public void setSearchWords(String searchWords) {
		this.searchWords = searchWords;
	}

	public String getSiteReferalPage() {
		return this.siteReferalPage;
	}

	public void setSiteReferalPage(String siteReferalPage) {
		this.siteReferalPage = siteReferalPage;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getReferedIpaddress() {
		return this.referedIpaddress;
	}

	public void setReferedIpaddress(String referedIpaddress) {
		this.referedIpaddress = referedIpaddress;
	}

}
